### ISSUE TITLE
Community site - back button doesn't work

### ISSUE THREAD

**Issue by tti0** [codeddraig/ffau#31]
This could possibly be intentional, knowing Pal's PHP tendencies, however, when on the Community site beta at http://cdbeta.hma-uk.org/, the following error ocurrs, in a new Firefox tab (issue also occurs in Google Chrome and on Firefox mobile for Android):

- One clicks on the blue "Sign Up" button by mistake, and is taken to the Sign Up page.
- However, the user actually wanted to read the contents of the home page, so presses the *web browser's* back button.
- Upon pressing this button, the _last loaded non-codedragon page_ is loaded, instead of the home page, in my case google.co.uk.

Thanks, @tti0.

**Comment by palkerecsenyi** [comment]
This issue occurs because buttons are literally <button> tags. I added some js so that you can add a data-link="" argument inside it. The js then reads the link inside this argument and runs window.location.replace, which replaces the window location rather than acting like a normal link, and therefore the browser doesn't register it as back button history.

**Comment by palkerecsenyi** [comment]
Issue fixed.
